### ISSUE TITLE
Support for filtering other sites?

### ISSUE THREAD

**Issue by RoboRay** [sellomkantjwa/unpinterested#3]
Is there a possibility of letting users add additional domains to be filtered from search queries?

**Comment by sellomkantjwa** [comment]
@RoboRay This is definitely the next step. Just haven't gotten around to it yet. Any pull requests are very welcome BTW.

**Comment by sellomkantjwa** [comment]
@RoboRay There is a more general version whisch allos you to do exactly that:
https://chrome.google.com/webstore/detail/google-search-blocklist/fldofmijlnlnghbdlnjblfnelihnelnm
